general:
  church_name: ''
  church_name_full: ''
  church_domain: ''
  production: true

baserow:
  api_uri: ''
  day_table_id: 0
  day_view_id: 0
  service_table_id: 0
  service_view_id: 0
  token: ''

cache:
  duration_in_seconds: 3600

church_suite:
  api_application: ''
  api_key: ''
  org: ''
  tag_id_adults: 1
  tag_id_children: 2

events:
  cancelled_flag: '[Cancelled]'
  default_location: 'Church'
  length_in_minutes: 60
  pending_flag: '[tbc]'
  timezone: 'Europe/London'

formats:
  csv_import_datetime: 'd-M-Yg:ia'
  display_date: 'D j M Y'
  display_day: 'D jS'
  display_day_and_month: 'j F'
  display_month: 'F Y'
  display_time: 'H:i'
  ics_date: 'Ymd'
  ics_datetime: 'Ymd\THis'
  json_datetime: 'Y-m-d\TH:i:sO'
  refresh_date: 'd/n'
  prayer_month_id: 'Y-m'
  sortable_date: 'Y-m-d'
  sortable_datetime: 'Y-m-d H:i'

login:
  admin: ''
  api: ''
  max_attempts: 5
  pass: ''

prayer:
  day_29: [ '' ]
  day_30: [ '' ]
  day_31: [ '' ]
  show_last_name: true

refresh:
  days_before: 7
  days_after: 2
  footer_page_1_left: 'If you don&rsquo;t know someone, or don&rsquo;t know what to say, you could pray...'
  footer_page_1_right: '<strong>&lsquo;Father, may <em>N</em> know your love, be filled with your Spirit, and share Jesus in all they do and say.&rsquo;</strong>'
  footer_page_2_left: 'Privacy Policy'
  footer_page_2_right: 'If you don&rsquo;t wish to be included, you can remove yourself in Church Suite or by contacting the office.'

rota:
  bible_version: 'NIVUK'
  default_days: 28
  default_length: 'PT90M'
  ministries:
    - { name: 'Intercessions', desc: 'Intercessor', abbv: 'I' }
    - { name: 'Preacher', abbv: 'Pr' }
    - { name: 'President', abbv: 'Ps' }
    - { name: 'Readings', desc: 'Reader', abbv: 'R' }
    - { name: 'Service Leader', desc: 'Leader', abbv: 'L' }
